//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snet.Yolo.Tool {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snet.Yolo.Tool.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [ Shunnet.top ] Yolo 调试工具 的本地化字符串。
        /// </summary>
        internal static string SystemTitle {
            get {
                return ResourceManager.GetString("SystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Yolo ] 的本地化字符串。
        /// </summary>
        internal static string Yolo {
            get {
                return ResourceManager.GetString("Yolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Yolo 分类 ] 的本地化字符串。
        /// </summary>
        internal static string YoloClassify {
            get {
                return ResourceManager.GetString("YoloClassify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Yolo 数据统一 ] 的本地化字符串。
        /// </summary>
        internal static string YoloDataUnification {
            get {
                return ResourceManager.GetString("YoloDataUnification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Yolo 检测 ] 的本地化字符串。
        /// </summary>
        internal static string YoloDetect {
            get {
                return ResourceManager.GetString("YoloDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Yolo 定向检测 ] 的本地化字符串。
        /// </summary>
        internal static string YoloOBB {
            get {
                return ResourceManager.GetString("YoloOBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Yolo 姿态 ] 的本地化字符串。
        /// </summary>
        internal static string YoloPose {
            get {
                return ResourceManager.GetString("YoloPose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Yolo 分割 ] 的本地化字符串。
        /// </summary>
        internal static string YoloSegment {
            get {
                return ResourceManager.GetString("YoloSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下标 的本地化字符串。
        /// </summary>
        internal static string 下标 {
            get {
                return ResourceManager.GetString("下标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个 的本地化字符串。
        /// </summary>
        internal static string 个 {
            get {
                return ResourceManager.GetString("个", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交互数据 的本地化字符串。
        /// </summary>
        internal static string 交互数据 {
            get {
                return ResourceManager.GetString("交互数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交并比阈值 的本地化字符串。
        /// </summary>
        internal static string 交并比阈值 {
            get {
                return ResourceManager.GetString("交并比阈值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改项 的本地化字符串。
        /// </summary>
        internal static string 修改项 {
            get {
                return ResourceManager.GetString("修改项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止验证 的本地化字符串。
        /// </summary>
        internal static string 停止验证 {
            get {
                return ResourceManager.GetString("停止验证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 像素置信度阈值 的本地化字符串。
        /// </summary>
        internal static string 像素置信度阈值 {
            get {
                return ResourceManager.GetString("像素置信度阈值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准度 的本地化字符串。
        /// </summary>
        internal static string 准度 {
            get {
                return ResourceManager.GetString("准度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类数量 的本地化字符串。
        /// </summary>
        internal static string 分类数量 {
            get {
                return ResourceManager.GetString("分类数量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能 的本地化字符串。
        /// </summary>
        internal static string 功能 {
            get {
                return ResourceManager.GetString("功能", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始图片 的本地化字符串。
        /// </summary>
        internal static string 原始图片 {
            get {
                return ResourceManager.GetString("原始图片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始图片路径 的本地化字符串。
        /// </summary>
        internal static string 原始图片路径 {
            get {
                return ResourceManager.GetString("原始图片路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        internal static string 参数 {
            get {
                return ResourceManager.GetString("参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string 名称 {
            get {
                return ResourceManager.GetString("名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向上验证 的本地化字符串。
        /// </summary>
        internal static string 向上验证 {
            get {
                return ResourceManager.GetString("向上验证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向下验证 的本地化字符串。
        /// </summary>
        internal static string 向下验证 {
            get {
                return ResourceManager.GetString("向下验证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片文件夹名称 的本地化字符串。
        /// </summary>
        internal static string 图片文件夹名称 {
            get {
                return ResourceManager.GetString("图片文件夹名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 坐标 的本地化字符串。
        /// </summary>
        internal static string 坐标 {
            get {
                return ResourceManager.GetString("坐标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理 的本地化字符串。
        /// </summary>
        internal static string 处理 {
            get {
                return ResourceManager.GetString("处理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理完成 的本地化字符串。
        /// </summary>
        internal static string 处理完成 {
            get {
                return ResourceManager.GetString("处理完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制结果 的本地化字符串。
        /// </summary>
        internal static string 复制结果 {
            get {
                return ResourceManager.GetString("复制结果", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        internal static string 大小 {
            get {
                return ResourceManager.GetString("大小", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储路径 的本地化字符串。
        /// </summary>
        internal static string 存储路径 {
            get {
                return ResourceManager.GetString("存储路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储路径为空 的本地化字符串。
        /// </summary>
        internal static string 存储路径为空 {
            get {
                return ResourceManager.GetString("存储路径为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对应硬件的JSON字符串 的本地化字符串。
        /// </summary>
        internal static string 对应硬件的JSON字符串 {
            get {
                return ResourceManager.GetString("对应硬件的JSON字符串", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已加载 的本地化字符串。
        /// </summary>
        internal static string 已加载 {
            get {
                return ResourceManager.GetString("已加载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始统计 的本地化字符串。
        /// </summary>
        internal static string 开始统计 {
            get {
                return ResourceManager.GetString("开始统计", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 张原图 的本地化字符串。
        /// </summary>
        internal static string 张原图 {
            get {
                return ResourceManager.GetString("张原图", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string 描述 {
            get {
                return ResourceManager.GetString("描述", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string 提示 {
            get {
                return ResourceManager.GetString("提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string 操作 {
            get {
                return ResourceManager.GetString("操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检索到图片 的本地化字符串。
        /// </summary>
        internal static string 未检索到图片 {
            get {
                return ResourceManager.GetString("未检索到图片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标注数据处理 的本地化字符串。
        /// </summary>
        internal static string 标注数据处理 {
            get {
                return ResourceManager.GetString("标注数据处理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        internal static string 标签 {
            get {
                return ResourceManager.GetString("标签", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签文件夹名称 的本地化字符串。
        /// </summary>
        internal static string 标签文件夹名称 {
            get {
                return ResourceManager.GetString("标签文件夹名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型路径 的本地化字符串。
        /// </summary>
        internal static string 模型路径 {
            get {
                return ResourceManager.GetString("模型路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        internal static string 消息 {
            get {
                return ResourceManager.GetString("消息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加项 的本地化字符串。
        /// </summary>
        internal static string 添加项 {
            get {
                return ResourceManager.GetString("添加项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string 清空 {
            get {
                return ResourceManager.GetString("清空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用时 的本地化字符串。
        /// </summary>
        internal static string 用时 {
            get {
                return ResourceManager.GetString("用时", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标 的本地化字符串。
        /// </summary>
        internal static string 目标 {
            get {
                return ResourceManager.GetString("目标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除项 的本地化字符串。
        /// </summary>
        internal static string 移除项 {
            get {
                return ResourceManager.GetString("移除项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束统计 的本地化字符串。
        /// </summary>
        internal static string 结束统计 {
            get {
                return ResourceManager.GetString("结束统计", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置信度阈值 的本地化字符串。
        /// </summary>
        internal static string 置信度阈值 {
            get {
                return ResourceManager.GetString("置信度阈值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节点已取消加载 的本地化字符串。
        /// </summary>
        internal static string 节点已取消加载 {
            get {
                return ResourceManager.GetString("节点已取消加载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        internal static string 菜单 {
            get {
                return ResourceManager.GetString("菜单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择模型路径 的本地化字符串。
        /// </summary>
        internal static string 请选择模型路径 {
            get {
                return ResourceManager.GetString("请选择模型路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择需要验证图片的文件夹 的本地化字符串。
        /// </summary>
        internal static string 请选择需要验证图片的文件夹 {
            get {
                return ResourceManager.GetString("请选择需要验证图片的文件夹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取失败 的本地化字符串。
        /// </summary>
        internal static string 读取失败 {
            get {
                return ResourceManager.GetString("读取失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续验证 的本地化字符串。
        /// </summary>
        internal static string 连续验证 {
            get {
                return ResourceManager.GetString("连续验证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string 选择 {
            get {
                return ResourceManager.GetString("选择", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择图片路径 的本地化字符串。
        /// </summary>
        internal static string 选择图片路径 {
            get {
                return ResourceManager.GetString("选择图片路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择存储路径 的本地化字符串。
        /// </summary>
        internal static string 选择存储路径 {
            get {
                return ResourceManager.GetString("选择存储路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择标签路径 的本地化字符串。
        /// </summary>
        internal static string 选择标签路径 {
            get {
                return ResourceManager.GetString("选择标签路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择父路径 的本地化字符串。
        /// </summary>
        internal static string 选择父路径 {
            get {
                return ResourceManager.GetString("选择父路径", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证 的本地化字符串。
        /// </summary>
        internal static string 验证 {
            get {
                return ResourceManager.GetString("验证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证图片异常 的本地化字符串。
        /// </summary>
        internal static string 验证图片异常 {
            get {
                return ResourceManager.GetString("验证图片异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证已停止 的本地化字符串。
        /// </summary>
        internal static string 验证已停止 {
            get {
                return ResourceManager.GetString("验证已停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证所有 的本地化字符串。
        /// </summary>
        internal static string 验证所有 {
            get {
                return ResourceManager.GetString("验证所有", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证结果 的本地化字符串。
        /// </summary>
        internal static string 验证结果 {
            get {
                return ResourceManager.GetString("验证结果", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证选中 的本地化字符串。
        /// </summary>
        internal static string 验证选中 {
            get {
                return ResourceManager.GetString("验证选中", resourceCulture);
            }
        }
    }
}
